//THIS IS A LIST OF DUMMY VARAIABLES
//I KNOW THIS IS THE DEFINITION OF SHITCODE BUT I HAVE DECIDED TO DO THIS IN 7 DAYS. CUT ME SOME SLACK
/obj/item/gun/ballistic/automatic/fallout
//THIS ONLY EXISTS FOR DUMMY VARIABLES

