//Each Faction has it's own area here

#define JOB_DISPLAY_ORDER_NCRCAPTAIN 		200
#define JOB_DISPLAY_ORDER_NCRLIEUTENANT		202
#define JOB_DISPLAY_ORDER_NCROFFICER		203
#define JOB_DISPLAY_ORDER_NCRREP			204
#define JOB_DISPLAY_ORDER_NCRSERGEANT		205
#define JOB_DISPLAY_ORDER_NCRSPECIALIST		206
#define JOB_DISPLAY_ORDER_NCRCORPORAL		207
#define JOB_DISPLAY_ORDER_NCRPRIVATE		208
#define JOB_DISPLAY_ORDER_NCRCONSCRIPT		209
<<<<<<< HEAD
#define JOB_DISPLAY_ORDER_NCRVET			210
#define JOB_DISPLAY_ORDER_NCRRANGER			211

#define JOB_DISPLAY_ORDER_CENTURION 		215
#define JOB_DISPLAY_ORDER_ORATOR			216
#define JOB_DISPLAY_ORDER_VETDEC			217
#define JOB_DISPLAY_ORDER_VENATOR			218
#define JOB_DISPLAY_ORDER_PRIMEDEC			219
#define JOB_DISPLAY_ORDER_RECRUITDEC		220
#define JOB_DISPLAY_ORDER_VEXIL				221
#define JOB_DISPLAY_ORDER_EXPLORER			222
#define JOB_DISPLAY_ORDER_VETERAN			223
#define JOB_DISPLAY_ORDER_PRIME				225
#define JOB_DISPLAY_ORDER_SLAVEMASTER       226
#define JOB_DISPLAY_ORDER_RECRUIT		    227
#define JOB_DISPLAY_ORDER_FORGEMASTER		228
#define JOB_DISPLAY_ORDER_IMMUNE			229
#define JOB_DISPLAY_ORDER_AUX				230
#define JOB_DISPLAY_ORDER_SLAVE				231

#define JOB_DISPLAY_ORDER_ENCLAVELT 		241
#define JOB_DISPLAY_ORDER_ENCLAVEGUN		242
#define JOB_DISPLAY_ORDER_ENCLAVESGT		243
#define JOB_DISPLAY_ORDER_ENCLAVESPEC		244
#define JOB_DISPLAY_ORDER_ENCLAVEPVT		245
#define JOB_DISPLAY_ORDER_ENCLAVESCI		246

#define JOB_DISPLAY_ORDER_BOSHP		 		250
#define JOB_DISPLAY_ORDER_BOSHK				251
#define JOB_DISPLAY_ORDER_BOSHS				252
#define JOB_DISPLAY_ORDER_BOSSP				253
#define JOB_DISPLAY_ORDER_BOSSK				254
#define JOB_DISPLAY_ORDER_BOSSS				255
#define JOB_DISPLAY_ORDER_BOSPA				256
#define JOB_DISPLAY_ORDER_BOSKN				257
#define JOB_DISPLAY_ORDER_BOSSC				258
#define JOB_DISPLAY_ORDER_BOSIN				259

#define JOB_DISPLAY_ORDER_FOAADMIN			260
#define JOB_DISPLAY_ORDER_FOADOC			261
#define JOB_DISPLAY_ORDER_FOASCI			262
#define JOB_DISPLAY_ORDER_FOAVOL			263
#define JOB_DISPLAY_ORDER_FOAGAR			264
=======
#define JOB_DISPLAY_ORDER_NCRREAR			210
#define JOB_DISPLAY_ORDER_NCRVET			211
#define JOB_DISPLAY_ORDER_NCRRANGER			212

#define JOB_DISPLAY_ORDER_FOAADMIN			220
#define JOB_DISPLAY_ORDER_FOADOC			221
#define JOB_DISPLAY_ORDER_FOASCI			222
#define JOB_DISPLAY_ORDER_FOAVOL			223
#define JOB_DISPLAY_ORDER_FOAGAR			224

#define JOB_DISPLAY_ORDER_ENCLAVELT 		231
#define JOB_DISPLAY_ORDER_ENCLAVEGUN		232
#define JOB_DISPLAY_ORDER_ENCLAVESGT		233
#define JOB_DISPLAY_ORDER_ENCLAVESPEC		234
#define JOB_DISPLAY_ORDER_ENCLAVEPVT		235
#define JOB_DISPLAY_ORDER_ENCLAVESCI		236

#define JOB_DISPLAY_ORDER_BOSHP		 		240
#define JOB_DISPLAY_ORDER_BOSHK				241
#define JOB_DISPLAY_ORDER_BOSHS				242
#define JOB_DISPLAY_ORDER_BOSSP				243
#define JOB_DISPLAY_ORDER_BOSSK				244
#define JOB_DISPLAY_ORDER_BOSSS				245
#define JOB_DISPLAY_ORDER_BOSPA				246
#define JOB_DISPLAY_ORDER_BOSKN				247
#define JOB_DISPLAY_ORDER_BOSSC				248
#define JOB_DISPLAY_ORDER_BOSIN				249

#define JOB_DISPLAY_ORDER_CENTURION 		250
#define JOB_DISPLAY_ORDER_ORATOR			251
#define JOB_DISPLAY_ORDER_VEX				252
#define JOB_DISPLAY_ORDER_VETDEC			253
#define JOB_DISPLAY_ORDER_PRIMEDEC			254
#define JOB_DISPLAY_ORDER_RECRUITDEC		255
#define JOB_DISPLAY_ORDER_VETERAN			256
#define JOB_DISPLAY_ORDER_PRIME				257
#define JOB_DISPLAY_ORDER_RECRUIT			258
#define JOB_DISPLAY_ORDER_VENATOR			259
#define JOB_DISPLAY_ORDER_EXPLORER			259
#define JOB_DISPLAY_ORDER_SLAVEMASTER		250
#define JOB_DISPLAY_ORDER_AUX				251
#define JOB_DISPLAY_ORDER_SLAVE				252
>>>>>>> b79cc4581000bec6c3d78fbc35745e8eb3c7a69a

#define JOB_DISPLAY_ORDER_TOWNMAYOR			270
#define JOB_DISPLAY_ORDER_TOWNSEC			271
#define JOB_DISPLAY_ORDER_TOWNSHOP			272
#define JOB_DISPLAY_ORDER_TOWNINN			273
#define JOB_DISPLAY_ORDER_TOWNPROS			274
#define JOB_DISPLAY_ORDER_TOWNFARM			275
#define JOB_DISPLAY_ORDER_TOWNCIT			276

#define JOB_DISPLAY_ORDER_CHIEF				277
#define JOB_DISPLAY_ORDER_OFFICER			278
#define JOB_DISPLAY_ORDER_DEPUTY			279

#define JOB_DISPLAY_ORDER_GREATKHAN			296
#define JOB_DISPLAY_ORDER_OUTLAW			297
#define JOB_DISPLAY_ORDER_TRIBAL			298
#define JOB_DISPLAY_ORDER_WASTELANDER		299


